import "./globals.css";
import "./fonts/font.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ScrollToTop from "@/components/ScrolltoTop/ScrollToTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  

  return (
    <html lang="fa" dir="rtl">
      <body
        className={''}
      >
        <Header/>
        <div className="max-w-screen min-w-screen ">
           
            {children}
        </div>
        <Footer/>
        <ScrollToTop/>
      </body>
    </html>
  );
}
